server:
  port: 5006
spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb?createDatabaseIfNotExist=true
    username: root
    password: 71571698
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone:  http://localhost:8070/eureka/



stripe:
  api:
    key: sk_test_51PorU5DmreDqVZUQXpR0ZUGIftOXcoUqrgQAd4L7SvBdwT3nTUPjetSS89e4gXpe6pI3WiwuvZYa5wGdQTfNBN2100i7z1ZxAU