services:

  userdb:
    image: mysql
    container_name: userdb
    ports:
      - 3301:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: "71571698"
      MYSQL_DATABASE: "userdb"
    networks:
      - milaanb

  bookingdb:
    image: mysql
    container_name: bookingdb
    ports:
      - 3302:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: "71571698"
      MYSQL_DATABASE: "bookingdb"
    networks:
      - milaanb

  categorydb:
    image: mysql
    container_name: categorydb
    ports:
      - 3303:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: "71571698"
      MYSQL_DATABASE: "categorydb"
    networks:
      - milaanb

  paymentdb:
    image: mysql
    container_name: paymentdb
    ports:
      - 3304:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: "71571698"
      MYSQL_DATABASE: "paymentdb"
    networks:
      - milaanb

  salondb:
    image: mysql
    container_name: salondb
    ports:
      - 3305:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: "71571698"
      MYSQL_DATABASE: "salondb"
    networks:
      - milaanb

  serviceofferingdb:
    image: mysql
    container_name: serviceofferingdb
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: "71571698"
      MYSQL_DATABASE: "serviceofferingdb"
    networks:
      - milaanb


  eurekaserver:
    image: "milaanb/salon-eureka-server:v1"
    ports:
      - "8070:8070"
    healthcheck:
      test: ["CMD", "curl --fail --silent eurekaserver:8070/actuator/health/readiness | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: eurekaserver
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - milaanb

  userservice:
    image: "milaanb/salon-user:v1"
    ports:
      - "5001:5001"
    healthcheck:
      test: ["CMD","curl --fail --silent userservice:5001/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: userservice
    depends_on:
      userdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "user-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://userdb:3306/userdb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "71571698"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - milaanb

  bookingservice:
    image: "milaanb/salon-booking:v1"
    ports:
      - "5005:5005"
    healthcheck:
      test: [ "CMD","curl --fail --silent bookingservice:5005/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: bookingservice
    depends_on:
      bookingdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "booking-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://bookingdb:3306/bookingdb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "71571698"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - milaanb

  categoryservice:
    image: "milaanb/salon-category:v1"
    ports:
      - "5003:5003"
    healthcheck:
      test: [ "CMD","curl --fail --silent categoryservice:5003/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: categoryservice
    depends_on:
      categorydb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "category-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://categorydb:3306/categorydb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "71571698"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - milaanb

  paymentservice:
    image: "milaanb/salon-payment:v1"
    ports:
      - "5006:5006"
    healthcheck:
      test: [ "CMD","curl --fail --silent paymentservice:5006/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: paymentservice
    depends_on:
      paymentdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "payment-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://paymentdb:3306/paymentdb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "71571698"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - milaanb

  salonservice:
    image: "milaanb/salon-salon-service:v1"
    ports:
      - "5002:5002"
    healthcheck:
      test: [ "CMD","curl --fail --silent salonservice:5002/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: salonservice
    depends_on:
      salondb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "salon-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://salondb:3306/salondb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "71571698"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - milaanb

  servicesofferingservice:
    image: "milaanb/salon-services-offering:v1"
    ports:
      - "5004:5004"
    healthcheck:
      test: [ "CMD","curl --fail --silent servicesofferingservice:5004/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: servicesofferingservice
    depends_on:
      serviceofferingdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "services-offering"
      SPRING_DATASOURCE_URL: "jdbc:mysql://serviceofferingdb:3306/serviceofferingdb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "71571698"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - milaanb


  gatewaysarver:
    image: "milaanb/salon-gateway-server:v1"
    ports:
      - "5000:5000"
    healthcheck:
      test: [ "CMD","curl --fail --silent gatewaysarver:5000/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: gatewaysarver
    environment:
      SPRING_APPLICATION_NAME: "gateway-server"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - milaanb


networks:
    milaanb:
        driver: "bridge"